version: "3.6"
services:
  migrations:
    network_mode: host
    build:
      context: ./messenger
      dockerfile: ./DockerfileMigrations
    env_file:
      - .env
    volumes:
      - ./messenger:/app


  messenger:
    restart: always
    network_mode: host
    depends_on:
      - migrations
    build:
      context: ./messenger
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "${MESSENGER_PORT}:8080"
    volumes:
      - ./messenger:/app

  celery_worker:
    restart: always
    network_mode: host
    build:
      context: ./messenger
      dockerfile: ./DockerfileWorker
    env_file:
      - .env
    volumes:
      - ./messenger:/app

  postprocessor:
    restart: always
    network_mode: host
    build:
      context: ./postprocessor
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "${POSTPROCESSOR_PORT}:8080"
    volumes:
      - ./postprocessor:/app
